name: Keep mirror up-to-date with original repo
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update mirrored repo
        uses: actions/checkout@v2
      - run: |
          git config --global user.email "mmar-migrate@users.noreply.github.com"
          git config --global user.name "mmar-migrate"
          git fetch "MAIN_REPO_URL"
          git reset --hard FETCH_HEAD
          mkdir -p .github/workflows/
          curl https://raw.githubusercontent.com/Magisk-Modules-Alt-Repo/mmar-migrate/master/extra/.github/workflows/update.yml > .github/workflows/update.yml
          git add .
          git commit -sam "AUTOMATED: Add automatic mirror fetching action"
          git push --force https://"${{ secrets.AUTH_NAME }}":"${{ secrets.AUTH_KEY }}"@github.com/Magisk-Modules-Alt-Repo/NEW_REPO_NAME
