name: Keep mirror up-to-date with original repo
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update mirrored repo
        uses: actions/checkout@v2
      - run: |
          LAST_COMMIT_ID=`git rev-parse HEAD`
          git fetch "MAIN_REPO_URL"
          git reset --hard FETCH_HEAD
          git cherry-pick "$LAST_COMMIT_ID"
          git push --force
