name: Migrate
on:
  workflow_dispatch:
    inputs:
      repo_user:
        description: 'Repo Username'
      repo_name:
        description: 'Repo Name'
      git_user:
        description: 'Authorized GitHub Username'
      git_token:
        description: 'Token Secret Name'
      mirror:
        description: 'Clone (0) or Mirror (1)'
        default: 0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Migrate
        id: migrate
        run: |
          git config --global user.email "${{ github.event.inputs.git_user }}@users.noreply.github.com"
          git config --global user.name "[Migrate] ${{ github.event.inputs.git_user }}"
          export GIT_USER="${{ github.event.inputs.git_user }}"
          export GIT_TOKEN="${{ secrets.${{ github.event.inputs.git_token }} }}"

          [[ "${{ github.event.inputs.mirror }}" -eq 1 ]] && MIRROR="-m"

          ./migrate $MIRROR ${{ github.event.inputs.repo_user }} ${{ github.event.inputs.repo_name }}
