name: Migrate
on:
  workflow_dispatch:
    inputs:
      repo_user:
        description: 'Repo Username'
      repo_name:
        description: 'Repo Name'
      git_user:
        description: 'Authorized GitHub Username'
      git_token:
        description: 'Authorized GitHub Token'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Migrate
        id: migrate
        run: |
          git config --global user.email "migrate@Magisk-Module-Alt-Repo.com"
          git config --global user.name "Migrate"
          export GIT_USER="${{ github.event.inputs.git_user }}"
          export GIT_TOKEN="${{ github.event.inputs.git_token }}"
          ./migrate ${{ github.event.inputs.repo_user }} ${{ github.event.inputs.repo_name }}
